#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_systemctl --service="$app" --action="stop"
ynh_config_remove_systemd
ynh_config_remove_nginx

# Remove log dir
ynh_safe_rm --file="/var/log/$app"

# Note: $install_dir + system_user + ports are auto-removed by YunoHost
# based on manifest [resources] declarations.

ynh_print_info --message="rclone Dashboard removed."
