#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

# Restore data snapshot
ynh_restore --origin_path="$install_dir/sources/data"
ynh_restore --origin_path="/etc/systemd/system/$app.service"
ynh_restore --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

# Re-fetch sources and re-build venv (smaller backup, faster restore)
ynh_setup_source --dest_dir="$install_dir" --keep="sources/data/"
setup_python_venv

systemctl daemon-reload
ynh_systemctl --service="$app" --action="start"
