#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_systemd_action --service_name="$app" --action="stop"

ynh_print_info --message="Updating sources…"
ynh_setup_source --dest_dir="$install_dir" --keep="data/"

ynh_print_info --message="Updating Python dependencies…"
ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade -r "$install_dir/requirements.txt"

ynh_add_nginx_config
ynh_add_systemd_config

ynh_systemd_action --service_name="$app" --action="start"
