#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_systemctl --service="$app" --action="stop"

ynh_print_info --message="Updating sources…"
ynh_setup_source --dest_dir="$install_dir" --keep="sources/data/"

ynh_print_info --message="Updating Python dependencies…"
ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade -r "$install_dir/sources/requirements.txt"

ynh_config_add_nginx
ynh_config_add_systemd

ynh_systemctl --service="$app" --action="start"
